apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-api
  labels:
    app: fitness-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-api
  template:
    metadata:
      labels:
        app: fitness-api
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY}/fitness-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: database-url
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: celery-result-backend
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: fitness-uploads-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-worker
  labels:
    app: fitness-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-worker
  template:
    metadata:
      labels:
        app: fitness-worker
    spec:
      containers:
      - name: worker
        image: ${DOCKER_REGISTRY}/fitness-worker:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: database-url
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: celery-result-backend
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: fitness-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-api
spec:
  selector:
    app: fitness-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitness-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: fitness-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2ZpdG5lc3NfdXNlcjpmaXRuZXNzX3Bhc3N3b3JkQHBvc3RncmVzOjU0MzIvZml0bmVzc19kYg==
  celery-broker-url: cmVkaXM6Ly9yZWRpczozNzkvMA==
  celery-result-backend: cmVkaXM6Ly9yZWRpczozNzkvMA==
